stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Build step - optional for TypeScript projects if tsc is needed"
    # - npx tsc   # Bỏ ghi chú nếu bạn dùng compile thủ công

unit-test-job:
  image: mcr.microsoft.com/playwright
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: always
    paths:
      - test-results/
      - playwright-report/
    expire_in: 1 week

lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - sleep 5
    - echo "Lint complete."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application deployed successfully."
